language: node_js
node_js:
  - "14.1.0"
script:
  - echo "deploying!"
install:
  - npm install --save-dev expo-cli && expo upgrade --non-interactive && npx expo login --non-interactive -u abbie && npm install 
after_success:
  - expo build:android --non-interactive
