language: node_js
node_js:
  - "14.1.0"
script:
  - echo "deploying!"
install:
  - npm install && expo upgrade --non-interactive && npm install --save-dev expo-cli && npx expo login --non-interactive -u abbie
after_success:
  - expo build:android --non-interactive
